---
# tasks file for anonymous-ftp

- name: Create configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/anonymous-ftp
    mode: 0755
    state: directory

- name: Create uploads directory
  become: true
  ansible.builtin.file:
    path: "{{ anonymous_ftp_incoming_data_dir }}"
    # UID of ftp in docker image
    owner: 21
    group: "{{ anonymous_ftp_incoming_group }}"
    mode: "u+wx,u-r,g+rwxs,o-rwx"
    state: directory

- name: Configuration files
  become: true
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: /etc/anonymous-ftp/{{ item }}
    mode: 0644
  # Uses private variable idrftp_anonymous_emails
  with_items:
    - vsftpd.banner
    - vsftpd.conf
    - vsftpd.email_passwords
  register: _anonymous_ftp_config

- name: Import a key for epel
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: Setup dnf repository, epel
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: Install docker
  become: true
  yum:
    name: python3-docker
    state: present

- name: Get Docker published ports list
  set_fact:
    anonymous_ftp_published_ports: >
      {{ anonymous_ftp_published_ports |
         default([anonymous_ftp_port | string + ':21']) +
         [item + ':' + item]
      }}
  with_sequence: >
    start={{ anonymous_ftp_pasv_min_port }}
    end={{ anonymous_ftp_pasv_max_port }}

- name: Run docker vsftpd
  become: true
  ansible.builtin.docker_container:
    image: "{{ anonymous_ftp_image }}"
    name: vsftpd
    published_ports: "{{ anonymous_ftp_published_ports }}"
    state: started
    restart: "{{ _anonymous_ftp_config is changed }}"
    restart_policy: always
    volumes:
      - "{{ anonymous_ftp_incoming_data_dir }}:/var/lib/ftp/incoming"
      - "/etc/anonymous-ftp:/etc/vsftpd:ro"
